// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcilCTk7NUlVI5oaLsGcIxxCGp7Ly6Tbs',
    appId: '1:1083450039264:web:52652078dbe88615ffe985',
    messagingSenderId: '1083450039264',
    projectId: 'opa-messenger-homolog',
    authDomain: 'opa-messenger-homolog.firebaseapp.com',
    storageBucket: 'opa-messenger-homolog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7mIYBS05or1YiX_-SSvkgGhhHofGElxQ',
    appId: '1:1083450039264:android:7e2f3b6468f56653ffe985',
    messagingSenderId: '1083450039264',
    projectId: 'opa-messenger-homolog',
    storageBucket: 'opa-messenger-homolog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrhfDBPaNDn8NtnQXBYLwU3GwHsdKFA08',
    appId: '1:1083450039264:ios:11c7cf2e57e6995dffe985',
    messagingSenderId: '1083450039264',
    projectId: 'opa-messenger-homolog',
    storageBucket: 'opa-messenger-homolog.appspot.com',
    iosClientId: '1083450039264-o271lcut2k3ue7dst19l2bj9griv73v5.apps.googleusercontent.com',
    iosBundleId: 'com.opa.opaMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrhfDBPaNDn8NtnQXBYLwU3GwHsdKFA08',
    appId: '1:1083450039264:ios:c2fb988839d896bdffe985',
    messagingSenderId: '1083450039264',
    projectId: 'opa-messenger-homolog',
    storageBucket: 'opa-messenger-homolog.appspot.com',
    iosClientId: '1083450039264-c9p5u2ik1in2pchgpis5f4iobcjkei7a.apps.googleusercontent.com',
    iosBundleId: 'com.opa.opaMessenger.RunnerTests',
  );
}
